In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as p
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import datasets
from sklearn import metrics
from sklearn.datasets import load_digits
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

import seaborn as sns


In [5]:

digit=load_digits()
x=digit.data 
y=digit.target

In [6]:
x_train,x_test,y_train ,y_test = train_test_split(x,y,test_size =0.3 )

In [7]:
x_train.shape,y_train.shape

((1257, 64), (1257,))

In [8]:
from sklearn.preprocessing import StandardScaler
x_std=StandardScaler().fit_transform(x)

In [9]:
from sklearn.decomposition import PCA
pca = PCA(n_components=40)

In [10]:
x_std=StandardScaler().fit_transform(x)

In [11]:
x_std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [13]:

principalComponentsprincipal  = pca.fit_transform(x_std)

In [14]:
from sklearn.linear_model import LogisticRegression
regression=LogisticRegression()

In [18]:
from sklearn.decomposition import PCA
pca = PCA(n_components=40)

In [19]:
principalComponents = pca.fit_transform(x_std)

In [20]:
principalDf = pd.DataFrame(data = principalComponents)

In [21]:
principalDf

0         1         2         3         4         5         6   \
0     1.914214 -0.954502 -3.946035  2.028722 -0.267172  0.530326 -1.415324   
1     0.588980  0.924636  3.924755 -1.779853 -0.993429 -0.675658  1.878565   
2     1.302039 -0.317189  3.023333 -2.043377 -2.081156  0.935116 -1.296201   
3    -3.020770 -0.868772 -0.801744 -2.187038 -0.556814  0.727120  0.959758   
4     4.528949 -1.093480  0.973121 -1.419510 -1.715106  1.431591  1.073653   
5    -1.301890 -1.148183 -1.574607 -2.413647 -0.630977  0.740803  1.306798   
6     1.434222 -2.957845  2.831278 -0.076952  0.523032  0.010903  0.983719   
7     0.614240  5.462184  0.658242  0.434429  0.850173 -0.954015 -1.833862   
8    -1.098451 -0.665823 -0.041023 -1.102525 -0.900724  0.755132 -0.966468   
9    -0.537970 -0.777493 -1.568922 -0.759984 -0.121344 -0.600995  0.675181   
10    3.378760 -0.495768 -2.280895  1.429204  0.006570 -0.150578 -0.739180   
11    2.063344  2.016679  1.540476 -4.773149 -2.194264  0.344463  3.084403   
12   -1.937011 -1.815247  2.801367 -0.786549  3.025776 -0.384557 -0.647715   
13   -3.258076  2.149124 -1.615647 -1.798929 -0.745367  1.828816  0.763425   
14    5.458744  0.025132  0.182527 -0.119621 -0.541031  0.104815  1.083117   
15   -3.877036  2.606816  1.858528  5.454026  0.615481  0.988485  3.602254   
16    0.921352 -3.262241  3.401443 -3.227337  1.096491  0.081962 -0.573131   
17    1.415335  1.954479  0.560574 -0.368824 -1.302535 -1.883612 -1.063240   
18   -0.926522  2.253017  1.532929  0.111959 -1.640291  0.261415 -0.069187   
19   -2.370963 -2.931915 -0.381362 -3.232762  2.084194  0.545311 -0.615777   
20    2.001901 -1.319746 -2.570949  0.855346 -0.565536 -1.017707 -0.812004   
21    1.694878  2.075387  0.885988 -4.388596 -1.446105 -0.307280  3.643113   
22   -3.114571 -1.058976  2.451496 -0.547892  0.761751 -0.012650 -1.890072   
23   -1.469418  3.910388 -2.078331 -0.869923  0.203791  0.689537 -0.288168   
24    4.003333 -0.322216  0.587683 -2.740552 -1.513549  0.676065  2.088564   
25   -0.376722  0.525118  1.356041  3.106103  0.926277 -1.029447  1.450079   
26    1.286726 -3.969443  2.542968  0.936670  0.282389  0.352676  1.026759   
27    3.842316  3.478237 -1.569506 -1.675841 -0.274117 -0.345087 -0.150025   
28   -0.166537  0.934112  1.259154 -0.086535 -1.045703  0.362908 -0.877884   
29   -2.014425 -2.376845 -0.707905 -3.515254  1.168346  0.694465  0.206820   
...        ...       ...       ...       ...       ...       ...       ...   
1767  4.958572 -1.159637  0.645671 -1.495313 -1.408076  0.580228  2.222095   
1768  1.009034 -3.325935 -0.584416  0.907491 -0.665941  0.398977 -1.279990   
1769 -0.542840 -0.492983 -3.138879  0.952803  0.732338 -1.169267  1.900093   
1770 -3.314655  1.510568 -0.820052 -1.838159 -1.474756  1.442497  2.178247   
1771  2.128214 -2.822365  3.623384 -1.087842 -0.085810  0.389352  1.443192   
1772 -1.814030  1.197999 -3.113638 -1.063800 -1.806722  0.021174  1.294914   
1773  1.374678 -4.417769  0.544578  0.931146  1.151819 -0.342558  0.125670   
1774  0.762953  0.643399  3.119026 -0.449233 -2.038237 -0.268279 -0.225335   
1775 -0.433045  3.216018  2.011168 -0.229290 -1.509357 -1.166810 -2.852438   
1776 -0.525867 -1.154642 -1.889820  0.953330  0.807080 -1.084717  1.495880   
1777  5.106682 -0.289142  0.341407 -1.773522 -2.469450  1.596730  0.885046   
1778  5.900098 -1.710240  1.858915  0.171253 -4.529246  4.714807  0.440303   
1779  1.597139  4.676427  0.469293 -0.503396 -0.074208 -1.780269 -2.551047   
1780 -5.137834 -0.191049  2.223967  2.046425 -0.885014  3.406912 -0.342169   
1781 -1.416098 -1.031485  1.196076  0.841544 -2.197926  2.483190  0.573312   
1782 -4.272989 -1.355840  3.059714  0.367667  1.045035  0.747248  0.006415   
1783 -3.136887 -1.411700  2.238424 -0.085147  0.779781  0.689966 -1.289871   
1784  1.568544 -0.438603 -1.840595 -0.847231  0.413573 -1.193723  2.474054   
1785  0.058277  1.978137  1.807598  1.282994 -1.856847 -0.847034 -3.167588   
1786 -0.711454  0.253346 -2.934788

In [22]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860155,
       0.0421412 , 0.03942083, 0.03389381, 0.02998221, 0.02932003,
       0.02781805, 0.02577055, 0.02275303, 0.0222718 , 0.02165229,
       0.01914167, 0.01775547, 0.01638069, 0.0159646 , 0.01489191,
       0.0134797 , 0.0127193 , 0.01165836, 0.01057647, 0.00975315,
       0.00944558, 0.00863011, 0.00836641, 0.00797691, 0.00746451,
       0.0072558 , 0.00691905, 0.00653897, 0.00640776, 0.00591343,
       0.00570869, 0.00523524, 0.00481626, 0.00453021, 0.00419432])

In [23]:
from sklearn.model_selection import train_test_split
principalDf_train,principalDf_test,y_train,y_test = train_test_split(principalDf,y,test_size = 0.3)

In [24]:
model=LogisticRegression()
model.fit(principalDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
pred=model.predict(principalDf_test)
pred

array([0, 0, 5, 6, 5, 5, 2, 8, 3, 8, 4, 7, 9, 4, 6, 5, 2, 3, 7, 1, 0, 2,
       7, 3, 5, 3, 6, 2, 2, 6, 7, 5, 6, 9, 0, 9, 4, 1, 7, 4, 5, 5, 3, 0,
       3, 7, 1, 0, 4, 8, 7, 7, 2, 0, 9, 8, 0, 2, 0, 1, 3, 5, 9, 1, 0, 5,
       8, 1, 7, 9, 7, 0, 1, 5, 9, 2, 0, 5, 0, 8, 0, 3, 7, 9, 1, 8, 5, 6,
       4, 0, 9, 6, 5, 0, 0, 8, 3, 8, 6, 6, 3, 9, 7, 2, 7, 6, 2, 1, 4, 0,
       6, 5, 2, 4, 6, 7, 0, 9, 4, 1, 9, 2, 1, 5, 1, 9, 7, 0, 5, 6, 9, 4,
       3, 2, 3, 5, 4, 1, 8, 8, 3, 8, 4, 3, 7, 1, 8, 1, 3, 0, 7, 8, 1, 5,
       0, 3, 4, 2, 6, 2, 3, 1, 1, 6, 2, 4, 2, 6, 9, 5, 3, 2, 6, 2, 6, 3,
       9, 9, 4, 4, 7, 0, 7, 7, 0, 6, 6, 0, 8, 2, 5, 6, 0, 4, 5, 1, 9, 7,
       9, 3, 8, 9, 4, 1, 8, 5, 2, 4, 8, 1, 5, 7, 5, 2, 6, 9, 1, 7, 6, 0,
       1, 1, 3, 7, 5, 8, 8, 2, 6, 7, 6, 5, 4, 6, 8, 7, 9, 2, 7, 5, 9, 5,
       8, 4, 4, 7, 1, 0, 5, 3, 2, 4, 8, 8, 9, 2, 2, 8, 5, 5, 6, 8, 0, 2,
       1, 0, 1, 3, 1, 0, 8, 0, 3, 3, 6, 9, 9, 9, 4, 2, 0, 1, 3, 3, 5, 3,
       5, 0, 4, 4, 9, 6, 7, 1, 2, 2, 3, 2, 0, 5, 0,

In [26]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9555555555555556

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.98      0.98      0.98        47
          1       0.91      0.96      0.94        54
          2       0.98      1.00      0.99        50
          3       0.96      0.93      0.95        58
          4       0.98      0.96      0.97        56
          5       0.98      0.94      0.96        63
          6       0.98      1.00      0.99        52
          7       0.97      1.00      0.98        57
          8       0.90      0.89      0.90        53
          9       0.90      0.90      0.90        50

avg / total       0.96      0.96      0.96       540

