In [0]:
wejhfaODH



NameError: ignored

In [0]:
import numpy as np
import math

In [0]:
a=np.random.rand(10,1)
print(a)
a.mean()

[[0.6991838 ]
 [0.53009396]
 [0.56076956]
 [0.40964564]
 [0.90149757]
 [0.43099501]
 [0.46534115]
 [0.7091545 ]
 [0.76360239]
 [0.9055489 ]]


0.6375832472503887

In [0]:
#question2

In [0]:
a=np.random.rand(20,1)
print(a)a.var()

SyntaxError: ignored

In [0]:
a=np.random.rand(20,1)
print(a)
a.var()

[[0.51014638]
 [0.95920456]
 [0.91497021]
 [0.45843647]
 [0.61282166]
 [0.23718301]
 [0.33529124]
 [0.99151753]
 [0.05875623]
 [0.71143106]
 [0.769679  ]
 [0.00810782]
 [0.73880286]
 [0.13689526]
 [0.5248758 ]
 [0.52241996]
 [0.49228445]
 [0.17324803]
 [0.77907996]
 [0.93940166]]


0.09095201834617118

In [0]:
#question3
A=np.random.rand(10,20)
print(A)
B=np.random.rand(20,25)
print(B)
C=np.dot(A,B)
print(C)

[[0.88244435 0.1489074  0.25022633 0.33536829 0.35758389 0.8926241
  0.4855304  0.39522979 0.24159488 0.0298547  0.3482034  0.40776558
  0.49588146 0.1667989  0.45571853 0.10583124 0.91648551 0.30779832
  0.535004   0.2524425 ]
 [0.49938923 0.54120817 0.43518096 0.45550761 0.15059169 0.86022376
  0.81218961 0.85012227 0.62010578 0.81684634 0.01018531 0.76936968
  0.35196266 0.85037379 0.59378545 0.27799887 0.53721027 0.54392419
  0.04399277 0.18308383]
 [0.81491351 0.16575227 0.79248376 0.68765843 0.95467366 0.57971587
  0.4820918  0.47889698 0.56313696 0.9735008  0.17092354 0.91654608
  0.24951296 0.19304971 0.06413806 0.11488606 0.35788991 0.86031093
  0.71346616 0.46385079]
 [0.78978234 0.24446364 0.74923008 0.62289186 0.13681836 0.15330353
  0.95185436 0.5962019  0.20037653 0.69863566 0.81625807 0.67160345
  0.09530315 0.84957863 0.88140395 0.22282659 0.31895136 0.48467387
  0.00870731 0.73708115]
 [0.74688155 0.03165527 0.48691123 0.89318112 0.41614254 0.65786578
  0.58080099 0.31

In [0]:
#question4
A=np.arange(10).reshape(10,1)
print(A)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [0]:
def f(x):
  return 1 /(1+math.exp(-x))
np.apply_along_axis(f, 1, A)


array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])